### PR TITLE
Avoid using CharsetEncoder of Android 4.x

### PR DESCRIPTION
**Pull request by komamitsu**
Android 4.x has a bug in CharsetEncoder where offset calculation is
wrong.
See
- https://github.com/msgpack/msgpack-java/issues/405
- https://github.com/msgpack/msgpack-java/issues/406

### CODE REVIEW

**Comment by komamitsu** [comment]
@frsyuki Can you review this change?

**Comment by frsyuki** [comment]
LGTM 👍 
Nice improvement. Please merge

**Comment by komamitsu** [comment]
Thanks!

**Comment by dbrgn** [comment]
Is a release containing this fix planned soon? :)

**Comment by komamitsu** [comment]
@dbrgn Released 0.8.12 that contains this fix.

**Comment by dbrgn** [comment]
@komamitsu Thanks a lot!

**Pull request merged**
