### PR TITLE
Fixes #38: Add IntegerValue.mostSuccinctMessageFormat

### LINKED ISSUE #38: IntegerValue should capture the size of the integer
The MessagePack serialized format knows the size of an Int, whether it's 8, 16, 32, or 64 bits.  However the current IntegerValue class loses this information, and it forces the user to pick the right method, getShort, getInt, etc.   It would be nice for IntegerValue to capture the original size of the integer when deserializing, and the same thing when it serializes.

### PR DESCRIPTION
**Pull request by xerial**
Add a utility method to IntegerValue to detect the most succinct integer type. This is useful when user wants to know which get method (e.g., getByte, getInt, etc. ) should be used to extract values.

### CODE REVIEW

**Comment by xerial** [comment]
@oza Could you review this change? I think this code is similar to your previous contribution to v06 (#38)

**Comment by oza** [comment]
@xerial LGTM overall. I have a question about a test: Does forAll method generate values based on the types at random?
http://doc.scalatest.org/2.2.4/#org.scalatest.prop.GeneratorDrivenPropertyChecks

If the answer is positive, we should add a test with values on the borders of types explicitly. Thoughts?

**Comment by xerial** [comment]
A nice thing about `forAll` method is it produces border values (e.g., Int.MaxValue, MinValue, 0, etc.) as well.

**Comment by oza** [comment]
OIC. +1, merging this shortly.

**Comment by oza** [comment]
Thanks @xerial for your contribution!

**Pull request merged**
