### PR TITLE
Add MessagePacker.totalWrittenBytes

### PR DESCRIPTION
**Pull request by xerial**
#195

### CODE REVIEW

**Comment by slandelle** [comment]
@xerial Is changing the formatting rules intended? It makes hard to tell what the PR modifications really are.

**Comment by xerial** [comment]
@slandelle sorry for the messing style change. I'm considering introducing some check-style plugins.

**Comment by slandelle** [comment]
Well, your project, your rules :)

**Comment by xerial** [comment]
@slandelle 
If you are OK, I'll release p6 based on this.

**Comment by slandelle** [comment]
Sure, thanks a lot!

**Pull request merged**
