### PR TITLE
Support numeric types in MessagePackParser.getText()

### PR DESCRIPTION
**Pull request by komamitsu**
Fixes https://github.com/msgpack/msgpack-java/issues/526

### CODE REVIEW

**Comment by komamitsu** [comment]
@xerial CI failed with this sbt failure. Any insights?

```
Run ./sbt test
Downloading sbt launcher for 1.2.8:
  From  http://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt/sbt-launch/1.2.8/sbt-launch.jar
    To  /home/runner/.sbt/launchers/1.2.8/sbt-launch.jar
Download failed. Obtain the jar manually and place it at /home/runner/.sbt/launchers/1.2.8/sbt-launch.jar
##[error]Process completed with exit code 1.
```

**Comment by xerial** [comment]
@komamitsu We need to update sbt-extra script because Maven has recently stopped supporting http:// repository.

**Comment by xerial** [comment]
We need to run this command to update sbt script:
```
curl -Ls https://git.io/sbt > ./sbt
```

**Comment by komamitsu** [comment]
@xerial Thanks!

**Pull request merged**
